using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Decia.Business.Common
{
    public enum AutoGeneratedRevisionType
    {
        InitialRevision,
        ComputationRevision,
    }

    public static class AutoGeneratedRevisionTypeUtils
    {
        public static readonly AutoGeneratedRevisionType? UserGeneratedRevision = null;
    }
}